services:
  backend:
    image: node:20-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    working_dir: /backend
    volumes:
      - ./backend:/backend

  frontend:
    image: node:20-alpine
    command: sh -c "npm install && npm run dev --host"
    ports:
      - 8000:8000
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
